name:                ravasz-regan-group
version:             0.1.0.0
github:              "githubuser/ravasz-regan-group"
license:             BSD3
author:              "Peter Regan"
maintainer:          "peter.regan@gmail.com"
copyright:           "2019 Peter Regan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Simulation, storage, and display of dynamically modular cell models
# category:            Scientific Computing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ravasz-regan-group#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Parsing
  - Types
  - ReadWrite
  - Utilities
  - Constants
  - Publish
#  ghc-options:
#  - -O2
  dependencies :
  - megaparsec
  - parser-combinators
  - fgl
  - vector
  - colour
  - text
  - scientific
  - unordered-containers
  - containers
  - HaTeX
  - validation
  - Unique
  - monoidal-containers
  - versions
  - hashable
  - safe-exceptions
  - bytestring
  - path
  - pretty-simple

executables:
  dynamicalCell:
    main:                DynamicalCell.hs
    source-dirs:         dynamicalCell

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N3
    - -main-is DynamicalCell.dynamicalCell
#    - -O2
    dependencies:
    - ravasz-regan-group
    - megaparsec
    - text
  dynamicalVerify:
    main:                DynamicalVerify.hs
    source-dirs:         dynamicalVerify
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N3
    - -main-is DynamicalVerify.dynamicalVerify
#    - -O2
    dependencies:
    - ravasz-regan-group
    - megaparsec
    - text
    - pretty-simple
    - path
    - path-io
    - optparse-applicative

tests:
  ravasz-regan-group-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
#    - -O2
    dependencies:
    - ravasz-regan-group
