name:                dynmod
version:             0.5.3.4
github:              "Ravasz-Regan-Group/dynmod"
license:             BSD3
author:              "Peter Regan"
maintainer:          "peter.regan@gmail.com"
copyright:           "2019 Peter Regan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Simulation, storage, and display of dynamically modular cell models
# category:            Scientific Computing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dynmod#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: 
  - src
  exposed-modules:
  - Parse.DMMS
  - Types.DMModel
  - Parse.GML
  - Types.GML
  - Compare
  - Visualize
  - ReadWrite
  - Utilities
  - Constants
  - Publish
  - SuppMat
  - Render
  - Text.LaTeX.Packages.Booktabs
  - Text.LaTeX.Packages.ColorTbl
  ghc-options:
  - -Wall
  - -O2
  - -j # Parallel compilation at the module level
  dependencies :
  - megaparsec
  - parser-combinators
  - fgl
  - vector
  - vector-instances
  - colour
  - text
  - scientific
  - unordered-containers
  - containers
  - HaTeX
  - validation
  - Unique
  - versions
  - hashable
  - safe-exceptions
  - bytestring
  - path
  - pretty-simple
  - mtl

executables:
  dynmod:
    main:                DynMod.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -O2
    - -Wall
    - -j # Parallel compilation at the module level
    dependencies:
    - dynmod
    - megaparsec
    - text
    - pretty-simple
    - path
    - path-io
    - optparse-applicative
    - fgl
    - HaTeX
    - mtl
    - validation

tests:
  dynmod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
#    - -O2
    dependencies:
    - dynmod
